import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import TopLoaderContext from "@/context/TopLoaderContext";
import { Suspense } from "react";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          ` flex flex-col items-center min-h-screen w-full dark`
        }
      >
        <Navbar />
        <Suspense>
          <TopLoaderContext>
            <main className="flex-1 w-full mx-auto">{children}</main>
          </TopLoaderContext>
        </Suspense>

        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
